-- MySQL Script generated by MySQL Workbench
-- Tue Aug 31 22:10:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spotify_rec_test_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spotify_rec_test_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify_rec_test_db` DEFAULT CHARACTER SET utf8 ;
USE `spotify_rec_test_db` ;

-- -----------------------------------------------------
-- Table `spotify_rec_test_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify_rec_test_db`.`user` ;

CREATE TABLE IF NOT EXISTS `spotify_rec_test_db`.`user` (
  `id` CHAR(45) NOT NULL,
  `access_token` VARCHAR(45) NOT NULL,
  `refresh_token` VARCHAR(45) NOT NULL,
  `expiration_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
